[workspace]
resolver = "2"
members = ["crates/df-core", "crates/dfabric", "crates/ui"]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[workspace.dependencies]
tokio = { version = "1", features = ["full"] }
rustls = { version = "0.23", default-features = false, features = ["ring", "std", "tls12", "logging"] }
tokio-rustls = { version = "0.26", default-features = false, features = ["ring", "tls12"] }
rustls-pki-types = "1"
rustls-pemfile = "2"
x509-parser = "0.16"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
hmac = "0.12"
hkdf = "0.12"
aes-gcm = "0.10"
p256 = { version = "0.13", features = ["ecdh", "ecdsa", "pkcs8", "pem", "std"] }
rand = "0.8"
base64 = "0.22"
uuid = { version = "1", features = ["v4"] }
thiserror = "2"
hex = "0.4"
async-trait = "0.1"
dirs = "6"
hostname = "0.4"
fs4 = "0.12"
libc = "0.2"
btleplug = "0.11"
mdns-sd = "0.13"
keyring = "3"
clap = { version = "4", features = ["derive"] }

[profile.release]
lto = "thin"
